### ISSUE TITLE
turbojpeg.h missing

### ISSUE THREAD

**Issue by madtulip** [pupil-labs/pyndsi#17]
I am triing to install the pupil source code on windows according to.:
https://github.com/pupil-labs/pupil/wiki/Dependencies-Installation-Windows

while installing pyndsi using

$ git clone https://github.com/pupil-labs/pyndsi
$ python setup.py install

one include file is missing
"ndsi\frame.c(454): fatal error C1083: Cannot open include file: 'turbojpeg.h': No such file or directory"
full console out is at http://pastebin.com/WKG2RTD5

what am i missing?

thanks a lot for your time!

**Comment by madtulip** [comment]
I downloaded and installed this.:
https://sourceforge.net/projects/libjpeg-turbo/files/1.5.1/libjpeg-turbo-1.5.1-vc64.exe/download?use_mirror=superb-sea2&download=&failedmirror=kent.dl.sourceforge.net
and update the entry in 
/pyndsi/setup.py to the installation path
`tj_dir = 'C:\\Program Files\\libjpeg-turbo64'`
not sure if that worked out in the end, but at least it compiles now.
should be added to
https://github.com/pupil-labs/pupil/wiki/Dependencies-Installation-Windows

**Comment by indirectlylit** [comment]
Encountered this today on macOS.

For future searchers, the README was recently updated in https://github.com/pupil-labs/pyndsi/pull/60 with guidance to `brew install libjpeg-turbo` (and `opencv` for `ffmpeg`)
