### ISSUE TITLE
Cannot install pyndsi on Ubuntu!

### ISSUE THREAD

**Issue by zhangp14** [pupil-labs/pyndsi#25]
I try to install pyndsi on Ubuntu by using the following code
 `sudo pip3 install git+https://github.com/pupil-labs/pyndsi`
However, the install was not successful. 
`Collecting git+https://github.com/pupil-labs/pyndsi
  Cloning https://github.com/pupil-labs/pyndsi to /tmp/pip-zhoagsrw-build
Installing collected packages: ndsi
  Running setup.py install for ndsi ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-zhoagsrw-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-ofj0op1m-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.5
    creating build/lib.linux-x86_64-3.5/ndsi
    copying ndsi/__init__.py -> build/lib.linux-x86_64-3.5/ndsi
    running build_ext
    building 'ndsi.frame' extension
    creating build/temp.linux-x86_64-3.5
    creating build/temp.linux-x86_64-3.5/ndsi
    creating build/temp.linux-x86_64-3.5/ndsi/h264
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/zhangping/.local/lib/python3.5/site-packages/numpy/core/include -I/home/zhangping/.local/lib/python3.5/site-packages/numpy/core/include -I/usr/include/python3.5m -c ndsi/frame.cpp -o build/temp.linux-x86_64-3.5/ndsi/frame.o -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    In file included from /home/zhangping/.local/lib/python3.5/site-packages/numpy/core/include/numpy/ndarraytypes.h:1788:0,
                     from /home/zhangping/.local/lib/python3.5/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                     from /home/zhangping/.local/lib/python3.5/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                     from ndsi/frame.cpp:491:
    /home/zhangping/.local/lib/python3.5/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
     #warning "Using deprecated NumPy API, disable it by " \
      ^
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/zhangping/.local/lib/python3.5/site-packages/numpy/core/include -I/home/zhangping/.local/lib/python3.5/site-packages/numpy/core/include -I/usr/include/python3.5m -c ndsi/h264/media_stream.cpp -o build/temp.linux-x86_64-3.5/ndsi/h264/media_stream.o -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    In file included from ndsi/h264/media_stream.cpp:19:0:
    ndsi/h264/media_stream.cpp: In member function ‘virtual void serenegiant::media::MediaStream::release()’:
    ndsi/h264/utilbase.h:106:25: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
            basename(__FILE__), __LINE__, __FUNCTION__, ## __VA_ARGS__)
                             ^
    ndsi/h264/media_stream.cpp:56:2: note: in expansion of macro ‘LOGI’
      LOGI("total input %u frames", frames);
      ^
    ndsi/h264/media_stream.cpp: In member function ‘int serenegiant::media::MediaStream::init(AVFormatContext*, const AVCodecID&)’:
    ndsi/h264/utilbase.h:128:25: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
            basename(__FILE__), __LINE__, __FUNCTION__, ## __VA_ARGS__)
                             ^
    ndsi/h264/media_stream.cpp:76:4: note: in expansion of macro ‘LOGE’
        LOGE("avformat_new_stream failed, errno=%d", errno);
        ^
    ndsi/h264/utilbase.h:128:25: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
            basename(__FILE__), __LINE__, __FUNCTION__, ## __VA_ARGS__)
                             ^
    ndsi/h264/media_stream.cpp:79:3: note: in expansion of macro ‘LOGE’
       LOGE("already initialized");
       ^
    ndsi/h264/media_stream.cpp: In member function ‘virtual int serenegiant::media::MediaStream::set_input_buffer(AVFormatContext*, const uint8_t*, const size_t&, const int64_t&)’:
    ndsi/h264/utilbase.h:106:25: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
            basename(__FILE__), __LINE__, __FUNCTION__, ## __VA_ARGS__)
                             ^
    ndsi/h264/media_stream.cpp:107:3: note: in expansion of macro ‘LOGI’
       LOGI("input %u frames", frames);
       ^
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/zhangping/.local/lib/python3.5/site-packages/numpy/core/include -I/home/zhangping/.local/lib/python3.5/site-packages/numpy/core/include -I/usr/include/python3.5m -c ndsi/h264/h264_decoder.cpp -o build/temp.linux-x86_64-3.5/ndsi/h264/h264_decoder.o -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    In file included from ndsi/h264/h264_decoder.cpp:21:0:
    ndsi/h264/h264_decoder.cpp: In constructor ‘serenegiant::media::H264Decoder::H264Decoder(const color_format_t&)’:
    ndsi/h264/utilbase.h:128:25: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
            basename(__FILE__), __LINE__, __FUNCTION__, ## __VA_ARGS__)
                             ^
    ndsi/h264/h264_decoder.cpp:73:5: note: in expansion of macro ‘LOGE’
         LOGE("avcodec_open2 failed with error %d:%s", result, av_error(result).c_str());
         ^
    ndsi/h264/utilbase.h:128:25: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
            basename(__FILE__), __LINE__, __FUNCTION__, ## __VA_ARGS__)
                             ^
    ndsi/h264/h264_decoder.cpp:80:4: note: in expansion of macro ‘LOGE’
        LOGE("Could not initialize codec context");
        ^
    ndsi/h264/utilbase.h:128:25: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
            basename(__FILE__), __LINE__, __FUNCTION__, ## __VA_ARGS__)
                             ^
    ndsi/h264/h264_decoder.cpp:83:3: note: in expansion of macro ‘LOGE’
       LOGE("Could not find codec");
       ^
    ndsi/h264/h264_decoder.cpp: In member function ‘int serenegiant::media::H264Decoder::set_input_buffer(uint8_t*, const size_t&, const int64_t&)’:
    ndsi/h264/utilbase.h:128:25: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
            basename(__FILE__), __LINE__, __FUNCTION__, ## __VA_ARGS__)
                             ^
    ndsi/h264/h264_decoder.cpp:140:5: note: in expansion of macro ‘LOGE’
         LOGE("avcodec_receive_frame returned error %d:%s", result, av_error(result).c_str());
         ^
    ndsi/h264/utilbase.h:128:25: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
            basename(__FILE__), __LINE__, __FUNCTION__, ## __VA_ARGS__)
                             ^
    ndsi/h264/h264_decoder.cpp:154:6: note: in expansion of macro ‘LOGE’
          LOGE("avcodec_receive_frame returned error %d:%s", result, av_error(result).c_str());
          ^
    ndsi/h264/utilbase.h:128:25: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
            basename(__FILE__), __LINE__, __FUNCTION__, ## __VA_ARGS__)
                             ^
    ndsi/h264/h264_decoder.cpp:162:4: note: in expansion of macro ‘LOGE’
        LOGE("avcodec_send_packet EAGAIN");
        ^
    ndsi/h264/utilbase.h:128:25: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
            basename(__FILE__), __LINE__, __FUNCTION__, ## __VA_ARGS__)
                             ^
    ndsi/h264/h264_decoder.cpp:165:4: note: in expansion of macro ‘LOGE’
        LOGE("avcodec_send_packet AVERROR_EOF");
        ^
    ndsi/h264/utilbase.h:128:25: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
            basename(__FILE__), __LINE__, __FUNCTION__, ## __VA_ARGS__)
                             ^
    ndsi/h264/h264_decoder.cpp:169:4: note: in expansion of macro ‘LOGE’
        LOGE("avcodec_send_packet returned error %d:%s", result, av_error(result).c_str());
        ^
    ndsi/h264/h264_decoder.cpp: In member function ‘int serenegiant::media::H264Decoder::get_output_buffer(uint8_t*, const size_t&, int64_t&)’:
    ndsi/h264/utilbase.h:128:25: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
            basename(__FILE__), __LINE__, __FUNCTION__, ## __VA_ARGS__)
                             ^
    ndsi/h264/h264_decoder.cpp:239:3: note: in expansion of macro ‘LOGE’
       LOGE("capacity is smaller than required");
       ^
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/zhangping/.local/lib/python3.5/site-packages/numpy/core/include -I/home/zhangping/.local/lib/python3.5/site-packages/numpy/core/include -I/usr/include/python3.5m -c ndsi/h264/h264_utils.cpp -o build/temp.linux-x86_64-3.5/ndsi/h264/h264_utils.o -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    In file included from ndsi/h264/h264_utils.cpp:19:0:
    ndsi/h264/h264_utils.cpp: In function ‘const bool serenegiant::media::is_iframe(const uint8_t*, const size_t&)’:
    ndsi/h264/utilbase.h:117:25: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
            basename(__FILE__), __LINE__, __FUNCTION__, ## __VA_ARGS__)
                             ^
    ndsi/h264/h264_utils.cpp:239:3: note: in expansion of macro ‘LOGW’
       LOGW("too short");
       ^
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/zhangping/.local/lib/python3.5/site-packages/numpy/core/include -I/home/zhangping/.local/lib/python3.5/site-packages/numpy/core/include -I/usr/include/python3.5m -c ndsi/h264/video_stream.cpp -o build/temp.linux-x86_64-3.5/ndsi/h264/video_stream.o -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/zhangping/.local/lib/python3.5/site-packages/numpy/core/include -I/home/zhangping/.local/lib/python3.5/site-packages/numpy/core/include -I/usr/include/python3.5m -c ndsi/h264/ffmpeg_utils.cpp -o build/temp.linux-x86_64-3.5/ndsi/h264/ffmpeg_utils.o -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    ndsi/h264/ffmpeg_utils.cpp: In function ‘void serenegiant::media::log_packet(const AVFormatContext*, const AVPacket*)’:
    ndsi/h264/ffmpeg_utils.cpp:36:17: warning: unused variable ‘time_base’ [-Wunused-variable]
         AVRational *time_base = &format_context->streams[packet->stream_index]->time_base;
                     ^
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/zhangping/.local/lib/python3.5/site-packages/numpy/core/include -I/home/zhangping/.local/lib/python3.5/site-packages/numpy/core/include -I/usr/include/python3.5m -c ndsi/h264/mp4_writer.cpp -o build/temp.linux-x86_64-3.5/ndsi/h264/mp4_writer.o -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    In file included from ndsi/h264/mp4_writer.cpp:19:0:
    ndsi/h264/mp4_writer.cpp: In constructor ‘serenegiant::media::Mp4Writer::Mp4Writer(const string&)’:
    ndsi/h264/utilbase.h:117:25: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
            basename(__FILE__), __LINE__, __FUNCTION__, ## __VA_ARGS__)
                             ^
    ndsi/h264/mp4_writer.cpp:44:3: note: in expansion of macro ‘LOGW’
       LOGW("failed to deduce output format from file extension, try mp4");
       ^
    ndsi/h264/utilbase.h:128:25: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
            basename(__FILE__), __LINE__, __FUNCTION__, ## __VA_ARGS__)
                             ^
    ndsi/h264/mp4_writer.cpp:51:4: note: in expansion of macro ‘LOGE’
        LOGE("avformat_alloc_output_context2 failed, err=%s", av_error(result).c_str());
        ^
    ndsi/h264/utilbase.h:128:25: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
            basename(__FILE__), __LINE__, __FUNCTION__, ## __VA_ARGS__)
                             ^
    ndsi/h264/mp4_writer.cpp:57:3: note: in expansion of macro ‘LOGE’
       LOGE("failed to create format context, result=%d", result);
       ^
    ndsi/h264/mp4_writer.cpp: In member function ‘virtual int serenegiant::media::Mp4Writer::add(serenegiant::media::MediaStream*)’:
    ndsi/h264/utilbase.h:128:25: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
            basename(__FILE__), __LINE__, __FUNCTION__, ## __VA_ARGS__)
                             ^
    ndsi/h264/mp4_writer.cpp:91:3: note: in expansion of macro ‘LOGE’
       LOGE("format context is null, already released?");
       ^
    ndsi/h264/utilbase.h:117:25: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
            basename(__FILE__), __LINE__, __FUNCTION__, ## __VA_ARGS__)
                             ^
    ndsi/h264/mp4_writer.cpp:103:5: note: in expansion of macro ‘LOGW’
         LOGW("unknown MediaStream");
         ^
    ndsi/h264/utilbase.h:128:25: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
            basename(__FILE__), __LINE__, __FUNCTION__, ## __VA_ARGS__)
                             ^
    ndsi/h264/mp4_writer.cpp:110:6: note: in expansion of macro ‘LOGE’
          LOGE("failed to init stream:result=%d", result);
          ^
    ndsi/h264/utilbase.h:117:25: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
            basename(__FILE__), __LINE__, __FUNCTION__, ## __VA_ARGS__)
                             ^
    ndsi/h264/mp4_writer.cpp:115:4: note: in expansion of macro ‘LOGW’
        LOGW("specific stream was already added");
        ^
    ndsi/h264/utilbase.h:128:25: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
            basename(__FILE__), __LINE__, __FUNCTION__, ## __VA_ARGS__)
                             ^
    ndsi/h264/mp4_writer.cpp:119:3: note: in expansion of macro ‘LOGE’
       LOGE("stream is null");
       ^
    ndsi/h264/mp4_writer.cpp: In member function ‘virtual int serenegiant::media::Mp4Writer::start()’:
    ndsi/h264/utilbase.h:128:25: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
            basename(__FILE__), __LINE__, __FUNCTION__, ## __VA_ARGS__)
                             ^
    ndsi/h264/mp4_writer.cpp:132:3: note: in expansion of macro ‘LOGE’
       LOGE("format context is null, already released?");
       ^
    ndsi/h264/utilbase.h:128:25: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
            basename(__FILE__), __LINE__, __FUNCTION__, ## __VA_ARGS__)
                             ^
    ndsi/h264/mp4_writer.cpp:142:5: note: in expansion of macro ‘LOGE’
         LOGE("avio_open failed, err=%s", av_error(result).c_str());
         ^
    ndsi/h264/utilbase.h:128:25: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
            basename(__FILE__), __LINE__, __FUNCTION__, ## __VA_ARGS__)
                             ^
    ndsi/h264/mp4_writer.cpp:146:4: note: in expansion of macro ‘LOGE’
        LOGE("format is null or no output file is specified.");
        ^
    ndsi/h264/utilbase.h:128:25: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
            basename(__FILE__), __LINE__, __FUNCTION__, ## __VA_ARGS__)
                             ^
    ndsi/h264/mp4_writer.cpp:152:4: note: in expansion of macro ‘LOGE’
        LOGE("avformat_write_header failed, err=%s", av_error(result).c_str());
        ^
    ndsi/h264/utilbase.h:128:25: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
            basename(__FILE__), __LINE__, __FUNCTION__, ## __VA_ARGS__)
                             ^
    ndsi/h264/mp4_writer.cpp:157:3: note: in expansion of macro ‘LOGE’
       LOGE("could not start because no MediaStream were added");
       ^
    x86_64-linux-gnu-g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.5/ndsi/frame.o build/temp.linux-x86_64-3.5/ndsi/h264/media_stream.o build/temp.linux-x86_64-3.5/ndsi/h264/h264_decoder.o build/temp.linux-x86_64-3.5/ndsi/h264/h264_utils.o build/temp.linux-x86_64-3.5/ndsi/h264/video_stream.o build/temp.linux-x86_64-3.5/ndsi/h264/ffmpeg_utils.o build/temp.linux-x86_64-3.5/ndsi/h264/mp4_writer.o -lrt -lturbojpeg -lavutil -lavformat -lavcodec -lswscale -o build/lib.linux-x86_64-3.5/ndsi/frame.cpython-35m-x86_64-linux-gnu.so -std=c++11
    /usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libturbojpeg.a(libturbojpeg_la-turbojpeg.o): relocation R_X86_64_32 against `.data' can not be used when making a shared object; recompile with -fPIC
    /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libturbojpeg.a: 无法添加符号: 错误的值
    collect2: error: ld returned 1 exit status
    error: command 'x86_64-linux-gnu-g++' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-zhoagsrw-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-ofj0op1m-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-zhoagsrw-build/
`

**Comment by swells42** [comment]
I am having this issue too. Did you find a solution?

**Comment by mkassner** [comment]
please delete /usr/lib/x86_64-linux-gnu/libturbojpeg.a

and try again!

**Comment by swells42** [comment]
Thank you mkassner, it now works!

**Comment by mkassner** [comment]
great to hear!
