### ISSUE TITLE
"unistd.h": No such file or directory

### ISSUE THREAD

**Issue by PolynomialDivision** [pupil-labs/pyndsi#26]
Hi,
I can't compile pyndsi on my Windows 10 pc,

    c:\users\xxx\pyndsi\ndsi\h264\utilbase.h(12): fatal error C1083: Datei (Include) kann nicht geöffnet werden: "unistd.h": No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2

**Comment by papr** [comment]
This is a known issued and fixed with #24 
I will test the PR and merge if I do not encounter problems.

**Comment by papr** [comment]
Ok, I did not encounter any problems on Linux.

@PolynomialDivision Please checkout the newest version and reopen this issue if you run into any problems!

**Comment by PolynomialDivision** [comment]
@papr 
I can't reopen ^^ But the PR doesn't work... You have to uncomment line 43

**Comment by papr** [comment]
Fixed with #27
