### ISSUE TITLE
Install fails on macOS 10.13.3, no member named shrink_to_fit

### ISSUE THREAD

**Issue by burknator** [pupil-labs/pyndsi#35]
Okay, nevermind. Nothing works, I don't have time for this. Going for a Linux install.

For reference:

---

When trying to install `pyndsi` in a conda environment like this:

```
# pip install git+https://github.com/pupil-labs/pyndsi
```

☝️ *Aside:* I use `pip` here instead of `pip3` because of my conda environment. If you follow the installation instructions found in the [Pupil docs](https://docs.pupil-labs.com/#macos-dependencies) you should use `pip3`.

I get this error:

```
# pip install git+https://github.com/pupil-labs/pyndsi
[Load of warnings]
ndsi/h264/mp4_writer.cpp:234:11: error: no member named 'shrink_to_fit' in 'std::vector<serenegiant::media::MediaStream *, std::allocator<serenegiant::media::MediaStream *> >'
                    streams.shrink_to_fit();
                    ~~~~~~~ ^
    13 warnings and 1 error generated.
    error: command 'gcc' failed with exit status 1

    ----------------------------------------
  Rolling back uninstall of ndsi
Command "/Users/patrick/.anaconda3/envs/pupil/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/76/5c2xqlbn09x1s8ljg2d25q5h0000gn/T/pip-rrnzrbfm-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/76/5c2xqlbn09x1s8ljg2d25q5h0000gn/T/pip-0jt50oql-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/76/5c2xqlbn09x1s8ljg2d25q5h0000gn/T/pip-rrnzrbfm-build/
```

After trying a lot of things out, I finally fixed this by installing `gcc` via brew:

```
# brew install gcc
```

This will install the latest available `gcc`, which is `7.3.0` in my case.

Problem is, brew links this with `gcc-7` instead of `gcc`, which is used by `pip`. So you have to go into `/usr/local/bin` and create a symlink (change the version depending on what brew installs when you do this):

```
# cd /usr/local/bin
# ln -s ../Cellar/gcc/7.3.0/bin/gcc-7 ./gcc
```

**Open a new shell** and try to install `pyndsi` again, now it should work:

```
# pip install git+https://github.com/pupil-labs/pyndsi
```

You probably should remove the symlink now, because you will forget about this and make you crazy when compiling something else in the future:

```
# cd /usr/local/bin
# rm gcc
```

---

Details on my setup for comparison with your setup:

I followed the setup instructions found [here](https://docs.pupil-labs.com/#macos-dependencies), except for Python, OpenCV and scipy, which I installed via conda. I also installed all non-git Python packages I could via conda (I think `msgpack_python` wasn't available via conda).

Before installing `gcc` via brew:

```
# gcc --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.4.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

After installing `gcc`via brew and symlinking:

```
# gcc --version
gcc (Homebrew GCC 7.3.0) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Pip & Python:

```
# pip --version
pip 9.0.1 from /Users/patrick/.anaconda3/envs/pupil/lib/python3.6/site-packages (python 3.6)

# python --version
Python 3.6.4 :: Anaconda, Inc.
```

---

I wasted about 2 hours to find this out, hope this helps someone.

**Comment by kemics** [comment]
Hello, everyone

I have got the same issue, but the guide above did not help me. I got the error in macOS 10.13 and 10.11 (tried both Python 3.6  and Python 3.5). Tried to specify `env CC`, but I received the same error message:
```
 <scratch space>:55:1: note: expanded from here
    "ndsi/h264/mp4_writer.cpp"
    ^
    ndsi/h264/mp4_writer.cpp:234:11: error: no member named 'shrink_to_fit' in 'std::vector<serenegiant::media::MediaStream *, std::allocator<serenegiant::media::MediaStream *> >'
                    streams.shrink_to_fit();
                    ~~~~~~~ ^
    13 warnings and 1 error generated.
    error: command '/usr/bin/clang' failed with exit status 1
```

**Comment by burknator** [comment]
@kemics Are you using conda too? Because I tried it again, without conda and it worked almost like they write it in the docs (maybe I should create a PR for the changes...).

**Comment by cortensinger** [comment]
Im not using conda, and have still not been able to find a way to get past this pyndsi installation error

<scratch space>:62:1: note: expanded from here
    "ndsi/h264/mp4_writer.cpp"
    ^
    ndsi/h264/mp4_writer.cpp:234:11: error: no member named 'shrink_to_fit' in 'std::vector<serenegiant::media::MediaStream *, std::allocator<serenegiant::media::MediaStream *> >'
                    streams.shrink_to_fit();
                    ~~~~~~~ ^
    13 warnings and 1 error generated.
    error: command '/usr/bin/clang' failed with exit status 1

Very sad... :(

**Comment by papr** [comment]
`shrink_to_fit` is a feature introduced in c++11, see http://www.cplusplus.com/reference/vector/vector/shrink_to_fit/

`pyndsi` is setup to use the c++11 standard during compilation. Please make sure that your compiler supports c++11 and uses its standard library correctly.

**Comment by performlabrit** [comment]
AS @papr suggested, the issue is that mac osx may be using outdated compilers.  This may be related to the use of anaconda.  After some googling, I've found a workaround, with a caveat (see below).

CFLAGS=-stdlib=libc++ pip3 install git+https://github.com/pupil-labs/pyndsi

The caveat is that I'm not quite sure what CFLAGS is modifying, if it's a temporary change for that terminal session or if will affect subsequent sessions and, if so, where that change is stored.  So, use at your own risk.

**Comment by burknator** [comment]
@performlabrit Writing it that way will only affect the current command, at most the current session. But it's certainly not permanent. That could also be a solution rather than a workaround.

**Comment by papr** [comment]
We provide wheels for all supported platforms now. No need for local builds anymore.
