### ISSUE TITLE
v 0.4 - CP36 Win64 wheel

### ISSUE THREAD

**Issue by cboulay** [pupil-labs/pyndsi#36]
[ndsi-0.4-cp36-cp36m-win_amd64.zip](https://github.com/pupil-labs/pyndsi/files/1869067/ndsi-0.4-cp36-cp36m-win_amd64.zip)

**Comment by mkassner** [comment]
@willpatera  should this be added to a release?

**Comment by willpatera** [comment]
Hi @cboulay I have updated the release with the `.whl` - https://github.com/pupil-labs/pyndsi/releases/tag/v0.4
