### ISSUE TITLE
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

### ISSUE THREAD

**Issue by ghost** [pupil-labs/pyndsi#37]
Running into an error while trying to run 
`pip3 install git+https://github.com/pupil-labs/pyndsi`

To the best of my knowledge all previous installation steps have been followed and have worked. Have tried the fix suggested in #25 but have no file `/usr/lib/x86_64-linux-gnu/libturbojpeg`.

Error Message:
`    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
    ndsi/h264/video_stream.cpp: In member function 'virtual int serenegiant::media::VideoStream::init_stream(AVFormatContext*, const AVCodecID&, AVStream*)':
    ndsi/h264/video_stream.cpp:77:2: error: 'AVCodecParameters' was not declared in this scope
      AVCodecParameters *params = stream->codecpar;
      ^
    ndsi/h264/video_stream.cpp:77:21: error: 'params' was not declared in this scope
      AVCodecParameters *params = stream->codecpar;
                         ^
    ndsi/h264/video_stream.cpp:77:38: error: 'AVStream {aka struct AVStream}' has no member named 'codecpar'
      AVCodecParameters *params = stream->codecpar;
                                          ^
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1`

**Comment by MarkVreoVernon** [comment]
I also have this error and dont have the file referenced in issue #25, I am installing on NVIDIA TX2. Did you manage to solve it?

**Comment by papr** [comment]
What is your output for running `ffmpeg -version` in a terminal?

**Comment by MarkVreoVernon** [comment]
ubuntu@tegra-ubuntu:~/libjpeg-turbo-1.5.1/libuvc/build/ceres-solver/build$ ffmpeg -version
ffmpeg version 2.8.15-0ubuntu0.16.04.1 Copyright (c) 2000-2018 the FFmpeg developers
built with gcc 5.4.0 (Ubuntu/Linaro 5.4.0-6ubuntu1~16.04.10) 20160609
configuration: --prefix=/usr --extra-version=0ubuntu0.16.04.1 --build-suffix=-ffmpeg --toolchain=hardened --libdir=/usr/lib/aarch64-linux-gnu --incdir=/usr/include/aarch64-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-libx264 --enable-libopencv
libavutil      54. 31.100 / 54. 31.100
libavcodec     56. 60.100 / 56. 60.100
libavformat    56. 40.101 / 56. 40.101
libavdevice    56.  4.100 / 56.  4.100
libavfilter     5. 40.101 /  5. 40.101
libavresample   2.  1.  0 /  2.  1.  0
libswscale      3.  1.101 /  3.  1.101
libswresample   1.  2.101 /  1.  2.101
libpostproc    53.  3.100 / 53.  3.100
ubuntu@tegra-ubuntu:~/libjpeg-turbo-1.5.1/libuvc/build/ceres-solver/build$

**Comment by papr** [comment]
> ffmpeg version 2.8.15

Please upgrade to ffmpeg 3 or higher. See this link for details: https://docs.pupil-labs.com/#install-linux-dependencies

**Comment by MarkVreoVernon** [comment]
I was following the linux dependencies section from this link, something is not working correctly at this ffmpeg3 step heres the output from the 3 steps.

ubuntu@tegra-ubuntu:~/libjpeg-turbo-1.5.1/libuvc/build/ceres-solver/build$ sudo add-apt-repository ppa:jonathonf/ffmpeg-3
 Backport and/or package of FFMPEG 3 and key libraries

***

Cumulative downloads at 2017-12-20: 68,504 (based on ffmpeg)

Total downloads of 3.4: 24,113
Total downloads of 3.3.2: 2,814

***

Find PPAs useful? Consider a donation to those you use.
 More info: https://launchpad.net/~jonathonf/+archive/ubuntu/ffmpeg-3
Press [ENTER] to continue or ctrl-c to cancel adding it

gpg: keyring `/tmp/tmpb4qd3ueo/secring.gpg' created
gpg: keyring `/tmp/tmpb4qd3ueo/pubring.gpg' created
gpg: requesting key F06FC659 from hkp server keyserver.ubuntu.com
gpg: /tmp/tmpb4qd3ueo/trustdb.gpg: trustdb created
gpg: key F06FC659: public key "Launchpad PPA for J Fernyhough" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
OK
ubuntu@tegra-ubuntu:~/libjpeg-turbo-1.5.1/libuvc/build/ceres-solver/build$ sudo apt-get update
Get:1 file:/var/cuda-repo-9-0-local  InRelease
Ign:1 file:/var/cuda-repo-9-0-local  InRelease
Get:2 file:/var/cuda-repo-9-0-local  Release [574 B]
Get:2 file:/var/cuda-repo-9-0-local  Release [574 B]
Ign:3 http://ppa.launchpad.net/bzindovic/suitesparse-bugfix-1319687/ubuntu xenial InRelease
Hit:4 http://ports.ubuntu.com/ubuntu-ports xenial InRelease              
Hit:5 http://ports.ubuntu.com/ubuntu-ports xenial-updates InRelease                  
Hit:6 http://ppa.launchpad.net/jonathonf/ffmpeg-3/ubuntu xenial InRelease            
Hit:7 http://ports.ubuntu.com/ubuntu-ports xenial-security InRelease
Ign:8 http://ppa.launchpad.net/bzindovic/suitesparse-bugfix-1319687/ubuntu xenial Release
Ign:9 http://ppa.launchpad.net/bzindovic/suitesparse-bugfix-1319687/ubuntu xenial/main arm64 Packages
Ign:10 http://ppa.launchpad.net/bzindovic/suitesparse-bugfix-1319687/ubuntu xenial/main all Packages
Ign:11 http://ppa.launchpad.net/bzindovic/suitesparse-bugfix-1319687/ubuntu xenial/main Translation-en_US
Ign:13 http://ppa.launchpad.net/bzindovic/suitesparse-bugfix-1319687/ubuntu xenial/main Translation-en
Ign:14 http://ppa.launchpad.net/bzindovic/suitesparse-bugfix-1319687/ubuntu xenial/main arm64 DEP-11 Metadata
Ign:15 http://ppa.launchpad.net/bzindovic/suitesparse-bugfix-1319687/ubuntu xenial/main DEP-11 64x64 Icons
Ign:9 http://ppa.launchpad.net/bzindovic/suitesparse-bugfix-1319687/ubuntu xenial/main arm64 Packages
Ign:10 http://ppa.launchpad.net/bzindovic/suitesparse-bugfix-1319687/ubuntu xenial/main all Packages
Ign:11 http://ppa.launchpad.net/bzindovic/suitesparse-bugfix-1319687/ubuntu xenial/main Translation-en_US
Ign:13 http://ppa.launchpad.net/bzindovic/suitesparse-bugfix-1319687/ubuntu xenial/main Translation-en
Ign:14 http://ppa.launchpad.net/bzindovic/suitesparse-bugfix-1319687/ubuntu xenial/main arm64 DEP-11 Metadata
Ign:15 http://ppa.launchpad.net/bzindovic/suitesparse-bugfix-1319687/ubuntu xenial/main DEP-11 64x64 Icons
Ign:9 http://ppa.launchpad.net/bzindovic/suitesparse-bugfix-1319687/ubuntu xenial/main arm64 Packages
Ign:10 http://ppa.launchpad.net/bzindovic/suitesparse-bugfix-1319687/ubuntu xenial/main all Packages
Ign:11 http://ppa.launchpad.net/bzindovic/suitesparse-bugfix-1319687/ubuntu xenial/main Translation-en_US
Ign:13 http://ppa.launchpad.net/bzindovic/suitesparse-bugfix-1319687/ubuntu xenial/main Translation-en
Ign:14 http://ppa.launchpad.net/bzindovic/suitesparse-bugfix-1319687/ubuntu xenial/main arm64 DEP-11 Metadata
Ign:15 http://ppa.launchpad.net/bzindovic/suitesparse-bugfix-1319687/ubuntu xenial/main DEP-11 64x64 Icons
Ign:9 http://ppa.launchpad.net/bzindovic/suitesparse-bugfix-1319687/ubuntu xenial/main arm64 Packages
Ign:10 http://ppa.launchpad.net/bzindovic/suitesparse-bugfix-1319687/ubuntu xenial/main all Packages
Ign:11 http://ppa.launchpad.net/bzindovic/suitesparse-bugfix-1319687/ubuntu xenial/main Translation-en_US
Ign:13 http://ppa.launchpad.net/bzindovic/suitesparse-bugfix-1319687/ubuntu xenial/main Translation-en
Ign:14 http://ppa.launchpad.net/bzindovic/suitesparse-bugfix-1319687/ubuntu xenial/main arm64 DEP-11 Metadata
Ign:15 http://ppa.launchpad.net/bzindovic/suitesparse-bugfix-1319687/ubuntu xenial/main DEP-11 64x64 Icons
Ign:9 http://ppa.launchpad.net/bzindovic/suitesparse-bugfix-1319687/ubuntu xenial/main arm64 Packages
Ign:10 http://ppa.launchpad.net/bzindovic/suitesparse-bugfix-1319687/ubuntu xenial/main all Packages
Ign:11 http://ppa.launchpad.net/bzindovic/suitesparse-bugfix-1319687/ubuntu xenial/main Translation-en_US
Ign:13 http://ppa.launchpad.net/bzindovic/suitesparse-bugfix-1319687/ubuntu xenial/main Translation-en
Ign:14 http://ppa.launchpad.net/bzindovic/suitesparse-bugfix-1319687/ubuntu xenial/main arm64 DEP-11 Metadata
Ign:15 http://ppa.launchpad.net/bzindovic/suitesparse-bugfix-1319687/ubuntu xenial/main DEP-11 64x64 Icons
Err:9 http://ppa.launchpad.net/bzindovic/suitesparse-bugfix-1319687/ubuntu xenial/main arm64 Packages
  404  Not Found
Ign:10 http://ppa.launchpad.net/bzindovic/suitesparse-bugfix-1319687/ubuntu xenial/main all Packages
Ign:11 http://ppa.launchpad.net/bzindovic/suitesparse-bugfix-1319687/ubuntu xenial/main Translation-en_US
Ign:13 http://ppa.launchpad.net/bzindovic/suitesparse-bugfix-1319687/ubuntu xenial/main Translation-en
Ign:14 http://ppa.launchpad.net/bzindovic/suitesparse-bugfix-1319687/ubuntu xenial/main arm64 DEP-11 Metadata
Ign:15 http://ppa.launchpad.net/bzindovic/suitesparse-bugfix-1319687/ubuntu xenial/main DEP-11 64x64 Icons
Reading package lists... Done                                                        
W: The repository 'http://ppa.launchpad.net/bzindovic/suitesparse-bugfix-1319687/ubuntu xenial Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://ppa.launchpad.net/bzindovic/suitesparse-bugfix-1319687/ubuntu/dists/xenial/main/binary-arm64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
ubuntu@tegra-ubuntu:~/libjpeg-turbo-1.5.1/libuvc/build/ceres-solver/build$ sudo apt install libavformat-dev libavcodec-dev libavdevice-dev libavutil-dev libswscale-dev libavresample-dev ffmpeg libav-tools x264 x265 libportaudio2 portaudio19-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libportaudio2 is already the newest version (19+svn20140130-1build1).
portaudio19-dev is already the newest version (19+svn20140130-1build1).
x264 is already the newest version (2:0.148.2643+git5c65704-1).
x265 is already the newest version (1.9-3).
ffmpeg is already the newest version (7:2.8.15-0ubuntu0.16.04.1).
libavcodec-dev is already the newest version (7:2.8.15-0ubuntu0.16.04.1).
libavdevice-dev is already the newest version (7:2.8.15-0ubuntu0.16.04.1).
libavformat-dev is already the newest version (7:2.8.15-0ubuntu0.16.04.1).
libavresample-dev is already the newest version (7:2.8.15-0ubuntu0.16.04.1).
libavutil-dev is already the newest version (7:2.8.15-0ubuntu0.16.04.1).
libswscale-dev is already the newest version (7:2.8.15-0ubuntu0.16.04.1).
libav-tools is already the newest version (7:3.4.4-1~16.04.york0).
The following packages were automatically installed and are no longer required:
  containerd libqmi-glib1 runc ubuntu-core-launcher
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 7 not upgraded.

**Comment by papr** [comment]
Please try
1. Uninstall: `sudo apt-get remove libavformat-dev libavcodec-dev libavdevice-dev libavutil-dev libswscale-dev libavresample-dev ffmpeg libav-tools x264 x265`
2. Reinstall: `sudo apt install libavformat-dev libavcodec-dev libavdevice-dev libavutil-dev libswscale-dev libavresample-dev ffmpeg libav-tools x264 x265`

**Comment by MarkVreoVernon** [comment]
I tried this and then sudo pip3 install git+https://github.com/pupil-labs/pyndsi
but I get the same error as previously reported.

thanks for supporting BTW.

**Comment by papr** [comment]
Our wheels now ship with all dependencies. No need to install dependencies anymore.
