### ISSUE TITLE
Windows installation process

### ISSUE THREAD

**Issue by nckshr** [pupil-labs/pyndsi#58]
Hello,

I am trying to get this up and running on a windows 10 machine. I'm to the point where I need to update the ffmpeg and turbo-jpeg entries in setup.py, but I can't seem to find analogs to the examples given... It looks like maybe I need the source code for ffmpeg? I have the executable but it seems that setup.py wants some headers and libs.

Also, I installed turbo-jpeg, but inside the lib folder all I have are .a files, not .lib files. Do I need to compile turbo-jpeg to generate these? 

If I have missed some detailed instructions somewhere, my apologies, but I couldn't seem to find them for windows.

**Comment by pfaion** [comment]
Hi @nckshr 
please excuse the poor documentation, we are currently in the process of making all our products easier to install on Windows, but we have not arrived at pyndsi yet.

Do you need to build pyndsi from source? We also provide precompiled Windows binaries in the form of a Python wheel. Go to [the release page](https://github.com/pupil-labs/pyndsi/releases) and download the latest `ndsi-*-cp36-cp36m-win_amd64.whl`.

Then you can install the downloaded wheel file from the command line with
```
pip install path/to/downloaded.whl
```

**Comment by pfaion** [comment]
I'll close this issue for now. Please report back if you need to run from source and are still experiencing issues, then I'll reopen the issue!

**Comment by nckshr** [comment]
ah, thanks I'll try the binaries! I don't think I need to compile from source, just wanted to experiment with my own client for streaming to a PC from pupil mobile and this looked like a great place to start. I will let you know if I run into any obstacles, thanks for the help!

**Comment by nckshr** [comment]
hmm, any chance you have a build for intel architecture? The one I'm seeing on the releases page appears to be amd

**Comment by papr** [comment]
@nckshr It is actually an Intel build (64-bit). Not sure what the story is behind `pip wheel` using `amd` in there on Windows.

**Comment by nckshr** [comment]
@papr @pfaion when I run pip3 install ndsi-1.3-cp36-cp36m-win_amd64.whl I get the following:
ERROR: ndsi-1.3-cp36-cp36m-win_amd64.whl is not a supported wheel on this platform.

I am running an intel i7 with windows 10 64bit and Python 3.8.2 64bit

Here's what I see when I open a python shell:
Python 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)] on win32

do I need a different version of python?

**Comment by pfaion** [comment]
@nckshr Your first observation is correct, currently we only provide Windows wheels for Python 3.6, as we use pyndsi mostly for the [Pupil Software Stack](https://github.com/pupil-labs/pupil), which currently does only run on Windows with Python 3.6 anyway due to other external dependencies.

A quick note: `amd64` is a general description of 64-bit architectures (an alternative form is e.g. x86_64), and is only named this way because AMD was the first to implement 64-bit architectures. However, it also works on intel!

Regarding your error, I'm not sure what is happening there. Apparently the library cannot find or load the compiled binary code shipped with the wheel. I checked that the wheel actually contains the binary code. Can you again check, maybe in a clean virtual environment? Please try to install pyre with
```
python -m pip install https://github.com/zeromq/pyre/archive/master.zip
```
since I remember we had problems in the past with the `-e` installation. And then again install the downloaded pyndsi wheel. I hope this solves the problem.

**Comment by nckshr** [comment]
@pfaion thanks for the tips! I tried anew on a fresh install of python3.6, unfortunately I get the same error after installing the wheel. For reference, here's my exact sequence of commands:

`git clone https://github.com/pupil-labs/pyndsi.git`
`cd pyndsi`
`python -m pip install https://github.com/zeromq/pyre/archive/master.zip`
(copy whl into pyndsi folder)
`python -m pip install .\ndsi-1.3-cp36-cp36m-win_amd64.whl`

**Comment by papr** [comment]
Hey, is it possible that you are running the import from the pyndsi repository clone root directory? This will import the `ndsi` folder in the direcotry that does not include the compiled data.

Please simply skip the cloning step. You should be able to perform the other steps from any directory, e.g. your Downloads folder.

**Comment by nckshr** [comment]
Oh, I didn't realize that would make a difference! So I started fresh doing everything except cloning the repo. Now I get a different error:
```
Python 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 24 2018, 00:16:47) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import ndsi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\Program Files\Python36\lib\site-packages\ndsi\__init__.py", line 24, in <module>
    from ndsi.formatter import DataFormat
  File "E:\Program Files\Python36\lib\site-packages\ndsi\formatter.py", line 10, in <module>
    from ndsi.frame import JPEGFrame, H264Frame, FrameFactory
ImportError: DLL load failed: The specified module could not be found.
```
Is there a dll I need to copy somewhere?

**Comment by pfaion** [comment]
@nckshr you will need the FFPMEG binaries on your path, we don't ship them with the pyndsi wheel.
Please download FFMPEG from: https://ffmpeg.zeranoe.com/builds/
Make sure to select the **4.x version**, **Win64** and **shared** linking.
After unpacking, you will need to add the `unpacked-ffmpeg-dir/bin` folder to you PATH environment variable.

**Comment by nckshr** [comment]
@pfaion  ah ok thanks, I'll give that a try. Will I need to do something similar for libjpeg-turbo?

**Comment by pfaion** [comment]
@nckshr No, we compile libjpeg-turbo as static library into the pyndsi binaries, since it's very small. For FFMPEG we did not do that, since it would blow up the wheel size and also precompiled binaries are "easily" available.

**Comment by nckshr** [comment]
@pfaion ah, makes sense. 

also - it works! I am now able to import ndsi without issue. I'll keep you posted as I try the examples but THANK YOU so much for all your help!! Hopefully this thread helps others trying to install on windows :)

**Comment by nckshr** [comment]
@pfaion now that I've got some of this working, my eventual goal is to be able to stream video over wifi from pupil mobile (I have a pupil core connected to the moto z2 play) at about 30fps. I figured this would be a good place to start, but I would appreciate any advice as to if I am on the right trail or not.

**Comment by pfaion** [comment]
Glad we could help! Would you mind creating a separate issue for this? I'll close this now, as the setup issue seems to be solved.
