### ISSUE TITLE
Microsoft Visual C++ 14.0 is required

### ISSUE THREAD

**Issue by pfaion** [pupil-labs/pyndsi#59]
When trying to build on a clean Windows machine, I get the following error:
```
  Building wheel for ndsi (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\PFA\work\pupil-invisible-monitor\.venv\Scripts\python.exe' 'C:\Users\PFA\work\pupil-invisible-monitor\.venv\lib\site-packages\pip\_vendor\pep517\_in_process.py' build_wheel 'C:\Users\PFA\AppData\Local\Temp\tmpqllogsj5'
       cwd: C:\Users\PFA\AppData\Local\Temp\pip-req-build-levng8ea
  Complete output (13 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.6
  creating build\lib.win-amd64-3.6\ndsi
  copying ndsi\formatter.py -> build\lib.win-amd64-3.6\ndsi
  copying ndsi\network.py -> build\lib.win-amd64-3.6\ndsi
  copying ndsi\sensor.py -> build\lib.win-amd64-3.6\ndsi
  copying ndsi\__init__.py -> build\lib.win-amd64-3.6\ndsi
  running build_ext
  building 'ndsi.frame' extension
  error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
  ----------------------------------------
  ERROR: Failed building wheel for ndsi
Failed to build ndsi
ERROR: Could not build wheels for ndsi which use PEP 517 and cannot be installed directly
```

I assume this worked previously because we only built on Windows machines that were set up to build the old Pupil versions from source.

**Comment by pfaion** [comment]
The fix is probably to add installing this to the docs for Windows dependencies.
Here are the old instructions for installing Visual Studio for Pupil pre v1.23:
https://github.com/pupil-labs/pupil/blob/bcc62d2426ab3db5ce4ac888673734e6eb352329/docs/dependencies-windows.md#install-visual-studio
Not sure if all of these are necessary for pyndsi. We'll have to check that at some point.

**Comment by papr** [comment]
Since we provide wheels for all dependencies now, we have removed the per-dependency instructions from the main repository. cibuildwheel will automatically choose the correct MSVC version.
