### ISSUE TITLE
Network API example does not connect

### ISSUE THREAD

**Issue by bhouDTU** [pupil-labs/pyndsi#67]
Hi, 

I tried to run the Network API example on your website: https://docs.pupil-labs.com/developer/invisible/#network-api

Both the phone hosting the Companion App and a laptop (MacBook Pro, M1) to run the example python code are connected to the same wifi (work wifi at university).

I started the Pupil Invisible recording on the phone app and ran the example code. The visulization on the phone works, but I see nothing in the live preview from the python code on the computer. Attached a screenshot. It seems "network.has_events" in the code always returned False. 

Your help would be much appreciated. 

Cheers,
James

<img width="538" alt="Screenshot 2021-06-28 at 16 15 23" src="https://user-images.githubusercontent.com/72058221/123651820-1789ce80-d82c-11eb-87ab-fed17609b156.png">

**Comment by papr** [comment]
You seem to have fixed https://github.com/pupil-labs/pupil/issues/2154 What did you change to get it working?

I was not able to reproduce the issue on older macOS versions. @romanroibu Please give this a try on your M1 mac.

It looks like this is a display issue in the app, but if `network.has_events` is always false, it might be possible that your network is dropping packets.

**Comment by bhouDTU** [comment]
Hi @papr,

I think pupil-labs/pupil#2154 is not working yet. I tried to install from source and there are some errors regarding pyglui,  NameError: name 'glew_header' is not defined.  I commented in [pupil-labs/pupil#2154](https://github.com/pupil-labs/pupil/issues/2154)

Sorry I am bit of a noob here, is this Network API example the same as what Pupil Invisible Monitor is trying to do? could it potentially be the same error that causes the Live Preview here to always be black and the gaze circle (red) to be constantly at top-left corner?

**Comment by papr** [comment]
Oh, yes, my apologies. It looked so similar to Pupil Invisible Monitor that I confused these two applications.
>  is this Network API example the same as what Pupil Invisible Monitor is trying to do?

Correct. The only difference is that the monitor app can manage multiple devices at the same time.

I ran the example and it worked as expected. I doubt this is a display issue as the example uses opencv instead of opengl for drawing. We have not seen opencv drawing issues on M1 macs yet. @romanroibu Please give the example a try nonetheless, please.

**Comment by bhouDTU** [comment]
Thanks. Would you let me know if you do anything specific for the network connection. If it enough that both the phone (app) and the laptop (Network API) are connected to the the same wifi? Or do I have to specify anything so that they detect each other?

Cheers,
James

**Comment by papr** [comment]
No, usually, if the network is permissive, the phone and computer should find each other automatically. Do you get any terminal output? It should say that it is connecting to sensors if the connection was successful.

**Comment by bhouDTU** [comment]
No, I didn't get any output. If I add the line `print(network.has_events)` it will just always be false. It seems `on_network_event` is never being called.

**Comment by bhouDTU** [comment]
Ok, it works now. I changed the wifi from the univeristy's work wifi to my personal mobile hotspot and I can see both world video and gaze position, as expected.
