### ISSUE TITLE
Can't intall pyndsi through setup.py, this error appears :

### ISSUE THREAD

**Issue by tletouze** [pupil-labs/pyndsi#68]
h264_decoder.cpp
ndsi/h264\h264_decoder.cpp(58): error C3861: 'avcodec_register_all' : identificateur introuvable
ndsi/h264\h264_decoder.cpp(59): error C2440: 'initialisation' : impossible de convertir de 'const AVCodec *' en 'AVCodec *'
ndsi/h264\h264_decoder.cpp(59): note: La conversion perd les qualificateurs
ndsi/h264\h264_decoder.cpp(124): warning C4267: '=' : conversion de 'size_t' en 'int', perte possible de données
ndsi/h264\h264_decoder.cpp(122): warning C4996: 'av_init_packet': a été déclaré déconseillé
ndsi/h264\h264_decoder.cpp(243): warning C4267: 'initialisation' : conversion de 'size_t' en 'int', perte possible de données
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30037\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

**Comment by papr** [comment]
Stale issue
