### ISSUE TITLE
Cython.Compiler.Errors.CompileError: ndsi/sensor.pyx

### ISSUE THREAD

**Issue by dmardanbeigi** [pupil-labs/pyndsi#7]
I get this error when I try to install pyndsi (I have glew version 2.0.0 installed):

         MacBook-Pro-2:pyndsi Diako$ python setup.py install
         Compiling ndsi/sensor.pyx because it changed.
         Cythonizing ndsi/sensor.pyx

         Error compiling Cython file:

            while self.has_data:
            # skip to newest frame
                data_msg = self.get_data(copy=False)
                meta_data = struct.unpack("<LLLLQLL", data_msg[1])
                if meta_data[0] == VIDEO_FRAME_FORMAT_MJPEG:
                    frame = JEPGFrame(*meta_data, data_msg[2])
                                                         ^

			ndsi/sensor.pyx:158:58: Non-keyword arg following star-arg
			Traceback (most recent call last):
			  File "setup.py", line 54, in <module>
			    ext_modules=cythonize(extensions)
			  File "/usr/local/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 865, in cythonize
			    cythonize_one(*args[1:])
			  File "/usr/local/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 985, in cythonize_one
			    raise CompileError(None, pyx_file)
			Cython.Compiler.Errors.CompileError: ndsi/sensor.pyx
			MacBook-Pro-2:pyndsi Diako$

**Comment by mkassner** [comment]
I m sure this was fixed? @papr

**Comment by papr** [comment]
Yes, this was fixed with f165d5757938e5c5a534fdbbd33090fe661dfe04
