### ISSUE TITLE
pyndsi windows setup not implemented

### ISSUE THREAD

**Issue by qian256** [pupil-labs/pyndsi#9]
When I was trying to run `python setup.py install` on Windows, it throws NotImplentedError.
From the code it seems that it is truly not implemented. When will the support be out?
Since this module is not frequently needed, commenting out the imports of ndsi_backend in the python3_opencv3 branch would temporarily solve the issue.

**Comment by willpatera** [comment]
Hi @qian256 - see https://github.com/pupil-labs/pyndsi/pull/6
